"""Enter thr first Number: 5
Enter thr second Number. : 10

Addition : 15
Subtraction : -5
Multiplication: 50
Division: 0.5"""

num1 = int(input("Enter first Number: "))
num2 = int(input("Enter second Number: "))

Addition = num1 + num2
Subtraction = num1 - num2
Multiplication = num1 * num2
Division = num1 / num2
print("Addition: ", Addition)
print("Subtraction: ", Subtraction)
print("Multiplication: ", Multiplication)
print("Division: ", Division)
